config/routes.rb
Jstays::Application.routes.draw do

  root  'static_pages#home'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :properties do
    resources :property_pics, shallow: true, only: [:index, :destroy, :create]
    resources :available_dates, shallow: true, only: [:index, :create, :update, :destroy, :set_all] do
      get :set_all, :on => :collection
    end
  end

  get '/search' => 'search#search', :as => 'search'
  get '/about', to: 'static_pages#about'
  get '/faq',   to: 'static_pages#faq'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/property.rb
class Property < ActiveRecord::Base

  geocoded_by :full_address
  before_validation :geocode
  before_create :before_creating
  before_validation :set_empty_rates

  belongs_to :user
  has_many :property_pics, dependent: :destroy
  has_many :available_dates, dependent: :destroy
  has_many :property_reviews, dependent: :destroy

  validates :title, :property_type, :sharing, :duration, :country, :city,
            :address, :bedrooms, :sleeps, presence: true
  validates :zip, presence: true, if: "['USA'].include?(country)"
  validates_presence_of :longitude, :latitude, :message => ' - We could not locate your address. Please correct the formatting.'

  validate :rate_set

  scope :available_between, ->(from, to) { joins(:available_dates).where("available_dates.a_date between ? and ?", from, to).uniq }

  def full_address
    "#{address}, #{city} #{zip}, #{country}"
  end
  def display_rate
    if duration.to_sym == :short_term
      "#{rate_daily_regular.to_i} #{currency.upcase} daily"
    else
      "#{rate_long_term.to_i} #{currency.upcase} per month"
    end
  end

  def rate_set
    if duration.to_sym == :short_term && rate_daily_regular == 0
      errors.add(:rate_daily_regular, '- Please set a payment rate.')
    elsif duration.to_sym == :long_term && rate_long_term == 0
      errors.add(:rate_long_term, '- Please set a payment rate.')
    end
  end

  def available_date(date_string)
    AvailableDate.where(property_id: self.id).where(:a_date => date_string.to_date).first
  end

  private
  def before_creating
    self.expires = 3.months.from_now
  end

  def set_empty_rates
    self.rate_daily_regular ||= 0
    self.rate_daily_high ||= 0
    self.rate_weekly_regular ||= 0
    self.rate_weekly_high ||= 0
    self.rate_monthly_regular ||= 0
    self.rate_monthly_high ||= 0
    self.rate_long_term ||= 0
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, :except => [:show, :new, :create]

  def index
    @properties = current_user.properties
  end

  def show
    @month_offset = params[:calendar_offset] ? params[:calendar_offset].to_i : 0
    @open_tab = params[:open_tab] || 'photos'
  end

  def new
    currency = current_user.currency if signed_in?
    @property = Property.new(currency: currency)
    flash.now[:notice] = "During our trial period, your posting will be accepted for free"
  end

  def create
    @property = Property.new(property_params)
    @property.amenities = params[:amenities].collect{|k, v| v}.join(",") if params[:amenities]
    unless signed_in?
      @user = User.new(user_params)
      @user.save
      sign_in @user
    end
    @property.user_id = params[:property][:user_id] || current_user.id
    if @property.save
      redirect_to @property, notice: 'Property was successfully created. You should add pictures of your property and set its availability.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    @property.amenities = params[:amenities].collect{|k, v| v}.join(",") if params[:amenities]
    if @property.update(property_params)
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @property.destroy
    redirect_to properties_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      allowed_params = [:user_id, :title, :description, :property_type, :sharing, :duration,
                    :currency, :other_expenses, :country, :state, :city, :zip, :address,
                    :floor, :bedrooms, :bathrooms, :sleeps, :kosher, :amenities, :comments1, :comments2,
                    :video_link, :active, :rate_long_term,
                    :rate_daily_regular, :rate_daily_high, :rate_weekly_regular,
                    :rate_weekly_high, :rate_monthly_regular, :rate_monthly_high]
      allowed_params.concat([:published]) if signed_in? && current_user.admin?
      params[:property].permit(allowed_params)
    end

    def user_params
      params[:user].permit(:email, :password, :password_confirmation)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.slim
= javascript_tag('$(function() { $("#property_city").chained("#property_country"); });')
= form_for(@property) do |f|

  -if @property.errors.any?
    #error_explanation
      h2
        | #{pluralize(@property.errors.count, "error")} prohibited this property from being saved:

      ul
      -@property.errors.full_messages.each do |msg|
        li
          = msg

  -if signed_in?
    = f.hidden_field(:user_id, value: current_user.id.to_s)
  -else
    #signup-line style='text-align: center;'
      .force-login.button
        /' I have an account
      .open-signin.button
        /| I do not have an account

  .smallGray
    | * indicates required field.

  table.regularForm align="center"
    tbody
      tr
        td valign="top"
          table
            tbody
              -if !signed_in?
                tr.property-signin
                  th
                    = label_tag :email
                  td
                    = text_field_tag :email, nil, class: 'text', name: 'user[email]'
                tr.property-signin
                  td.formSpace colspan="2"
                tr.property-signin
                  th
                    = label_tag :password
                  td
                    = password_field_tag :password, nil, class: 'text', name: 'user[password]'
                tr.property-signin
                  td.formSpace colspan="2"
                tr.property-signin
                  th
                    = label_tag :password_confirmation, "Confirmation"
                  td
                    = password_field_tag :password_confirmation, nil, class: 'text', name: 'user[password_confirmation]'
                tr.property-signin
                  td.formSpace colspan="2"
              tr
                th
                  = f.label :title, '*Title:'
                td
                  = f.text_field :title, class: 'text'
              tr
                td.formSpace colspan="2"
              tr
                th
                  = f.label :description
                td
                  = f.text_area :description
              tr
                td.formSpace colspan="2"
              tr
                th
                  = f.label :property_type
                td
                  = f.select(:property_type, PropertyTypes.collect {|k,v| [v,k]})
              tr
                td.formSpace colspan="2"
              tr
                th
                  |Sharing
                td
                  - Sharing.each do |k, v|
                    = f.radio_button(:sharing, k)
                    = f.label("sharing_#{k}".to_sym, v)
              tr
                td.formSpace colspan="2"
              tr
                th
                  |Duration
                td
                  - Duration.each do |k, v|
                    = f.radio_button(:duration, k, onclick: "duration_click('#{k}')")
                    = f.label("duration_#{k}".to_sym, v)
              tr
                th
                  = f.label :currency
                td
                  = f.select(:currency, Currencies)
              tr
                td.formSpace colspan="2"
              tr
                th
                  |Rates
                td#rate-fields-parent
                  table#short_term_rate_fields
                    tbody
                      tr
                        th
                        th Regular
                        th High Season
                      tr
                        td Daily
                        td
                          = f.text_field(:rate_daily_regular, maxlength: "7", :value => (number_with_precision(f.object.rate_daily_regular, :precision => 2) || 0))
                        td
                          = f.text_field(:rate_daily_high, maxlength: "7", :value => (number_with_precision(f.object.rate_daily_high, :precision => 2) || 0))
                      tr
                        td Weekly
                        td
                          = f.text_field(:rate_weekly_regular, maxlength: "7", :value => (number_with_precision(f.object.rate_weekly_regular, :precision => 2) || 0))
                        td
                          = f.text_field(:rate_weekly_high, maxlength: "7", :value => (number_with_precision(f.object.rate_weekly_high, :precision => 2) || 0))
                      tr
                        td Monthly
                        td
                          = f.text_field(:rate_monthly_regular, maxlength: "7", :value => (number_with_precision(f.object.rate_monthly_regular, :precision => 2) || 0))
                        td
                          = f.text_field(:rate_monthly_high, maxlength: "7", :value => (number_with_precision(f.object.rate_monthly_high, :precision => 2) || 0))
                  #long_term_rate_fields
                    = f.text_field :rate_long_term, maxlength: '27', :value => (number_with_precision(f.object.rate_long_term, :precision => 2) || 0)
              tr
                td.formSpace colspan="2"
              tr
                th
                  = f.label :other_expenses
                td valign="top"
                  = f.text_area :other_expenses
                td
                  span class='gitb-tooltip toolTip' title='Enter cleaning fee, realtor fee, maintenance fee and any other fees here.'
              tr
                td.formSpace colspan="2"
              tr
                th
                  = f.label :country, '*Country'
                td
                  = f.select :country, Countries.sort, {}, id: 'property_country'
              tr
                td.formSpace colspan="2"
              tr
                -city_select = Locations.collect { |country_name, country_info | country_info[:cities].collect {|city| [city, city, class: country_name] }.sort_by { |(city)| [city == "Other" ? 1 : 0, city]}.push(["Other"]) }.flatten(1)
                th
                  = f.label :city, '*City'
                td
                  = f.select :city, city_select, {}, id: 'property_city'
              tr
                td.formSpace colspan="2"
              tr.other-city-block
                th
                td
                  = text_field_tag(:other_city, nil, class: 'text')
              tr.other-city-block
                td.formSpace colspan="2"
              tr.zip-block
                th
                  = f.label :zip, '*Zip:'
                td
                  = f.text_field :zip, class: 'text'
              tr.zip-block
                td.formSpace colspan="2"
              tr
                -title = 'Your address field is required in order to display services in your neighborhood. We will never display your exact location.'
                th
                  = f.label :address, '*Address'
                td
                  = f.text_area :address
              tr
                td colspan=2
                  = title
        td width="50px"
        td width="50px" style="border-left:1px solid #A6CEFA;"
          td valign="top"
            table
              tbody
                tr
                  th
                    = f.label :floor
                  td
                    = f.select(:floor, Floors.collect {|k,v| [v,k]})
                tr
                  td.formSpace colspan="2"
                tr
                  th
                    = f.label :bedrooms, "No. of Bedrooms"
                  td
                    = f.select(:bedrooms, Bedrooms)
                tr
                  td.formSpace colspan="2"
                tr
                  th
                    = f.label :sleeps
                  td
                    = f.select(:sleeps, Sleeps)
                  td
                    span class='gitb-tooltip toolTip' title='This number may be approximate. We recommend one per twin and two per double, queen and king.'
                tr
                  td.formSpace colspan="2"
                tr
                  th
                    = f.label :bathrooms, "No. of Bathrooms"
                  td
                    = f.select(:bathrooms, Bathrooms)
                tr
                  td.formSpace colspan="2"
                tr
                  th
                    = f.label(:kosher, "Kosher?")
                  td
                    = f.check_box(:kosher)
                tr
                  td.formSpace colspan="2"
                tr
                  th
                    = f.label(:comments1, "Comments")
                  td
                    = f.text_area(:comments1)
                  td
                    span class='gitb-tooltip toolTip' title='Please feel free to describe the standards you require for keeping the kitchen kosher.'
                tr
                  td.formSpace colspan="2"
                tr
                  th
                    = f.label(:comments2, "General Comments")
                  td
                    = f.text_area(:comments2)
                  td
                    span class='gitb-tooltip toolTip' title='Use this field to enter check in /check out, cancellation, pet, smoking etc. policies.'
                tr
                  td.formSpace colspan="2"
                tr
                  th
                    = f.label(:video_link, 'Youtube Link')
                  td
                    = f.text_field(:video_link, class: 'text')
                  td
                    span class='gitb-tooltip toolTip' title='Enter the link of the Youtube video of your property. Example: http://www.youtube.com/watch?v=cevG1PVk or http://youtu.be/cevhhVk/'
                tr
                  td.formSpace colspan="2"
                tr
                  th
                    = f.label(:active, 'Active')
                  td
                    = f.check_box(:active)
                  td
                    span class='gitb-tooltip toolTip' title='Please mark property as active if it is currently available.  Please mark inactive if you are not currently taking reservations for the property but you may be interested in doing so in the future.'

  #edit-amenities
    h2 Amenities
    -Amenities.each_with_index do |amenity, index|
      .amenity-item
        =' check_box_tag "amenities[#{index}]", amenity, (@property.amenities.include?(amenity) if @property.amenities)
        = label_tag("amenities_#{index}", amenity)
      = "<br>".html_safe if index%5 == 4

  .actions
    = f.submit "Submit", class: "btn btn-primary btn-large"

app/views/properties/_sub_menu.html.slim
.mini_menu_div
	table.mini_menu align="center"
		tbody
			tr
				th
				th
					div
						= @property.title + " (" + @property.id.to_s + ")"
					'Posted:
					span = @property.created_at.to_s 
					' Expires:
					span = @property.expires.to_s
				th
				td
					= link_to "", property_path(@property), class: "view_button"
				td
					= link_to "", edit_property_path(@property), class: "edit_button"
				td
					= link_to "", property_property_pics_path(@property), class: "pics_button"
				td
					= link_to "", property_available_dates_path(@property), class: "availability_button"

app/views/properties/edit.html.slim
.h1_wrapper
	h1 Update property
.main_area
	= render "/properties/sub_menu"
	.intro_area
		|Intro to edit page goes here

	= render 'form'

app/views/properties/index.html.slim
.h1_wrapper
	h1 Listing properties
.main_area
	.intro_area
		|This is the intro text for the property listing page
	table.list_table
		thead
			tr
				th ID
				th Title
				th Expires
				th View
				th Edit

		tbody
			-tclass = "not-blue"
			-@properties.each do |property|
				-tclass = tclass=="blue" ? "not-blue" : "blue"
				tr class="#{tclass}"
					td 
						= property.id
					td
						= link_to property.title, property
					td
						= property.expires.to_s
					td
						= link_to 'Go', property, class:"go_button"
					td
						= link_to 'Go', edit_property_path(property), class:"go_button"
					/ td
					/ 	= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' }

	<br>

	= link_to 'CREATE A NEW PROPERTY', new_property_path

app/views/properties/new.html.slim
.h1_wrapper
  h1 Enter New Property
.main_area
  .intro_area
    |Use this form to enter a property into the system.

  = render 'form'

app/views/properties/show.html.slim
= javascript_include_tag("//maps.googleapis.com/maps/api/js?libraries=places&sensor=false&key=AIzaSyAUHE7DBIl5AsXATHDYb8K4azS0l5x2jL4")

-viewing_own_property = signed_in? && (current_user.id = @property.user_id)
.h1_wrapper
  h1 = @property.title + " (# " + @property.id.to_s + ")"
  h2
    | #{@property.property_type} in #{@property.city} for #{@property.duration}

.main_area
  - if admin_user? || viewing_own_property
    = render "/properties/sub_menu", property: @property

  table#rating_table
  table
    tbody
      tr
        / Left side
        td valign="top"

          #main_info
            table.tabs align="center"
              tbody
                tr
                  th
                  td#photos_tab class="#{@open_tab == 'photos' ? 'selected' : 'unselected'}"
                    = link_to 'Photos', 'javascript:void(0)', onclick: "switch_tab('photos', 'main_tabs')"
                  td#calendar_tab class="#{@open_tab=='calendar' ? 'selected' : 'unselected'}"
                    = link_to 'Calendar', 'javascript:void(0)', onclick: "switch_tab('calendar', 'main_tabs')"
                  td#map_tab class="#{@open_tab=='map' ? 'selected' : 'unselected'}"
                    = link_to 'Map', 'javascript:void(0)', onclick: "switch_tab('map', 'main_tabs')"
                  td#reviews_tab class="#{@open_tab=='reviews' ? 'selected' : 'unselected'}"
                    = link_to 'Reviews', 'javascript:void(0)', onclick: "switch_tab('reviews', 'main_tabs')"

            #current_content
              -hidden = 'position:absolute; top:0; left:-9999px;'
              -open = 'text-align: center;'
              #photos style="#{@open_tab == 'photos' ? open : hidden}"
                = render "/property_pics/embedded_pics", property: @property
              #calendar style="#{@open_tab == 'calendar' ? open : hidden}"
                .main_info_text
                = render "/available_dates/embedded_calendar"
              #map style="#{@open_tab == 'map' ? open : hidden}"
                .main_info_text
                  | Click a
                  span.circle1.synogogue-circle
                  | to see a neighborhood synogogue.
                  br
                  | Click a
                  span.circle1.restaurant-circle
                  | to view a kosher restaurant in the neighborhood.
                #map-canvas-holder style="height: 600px; width:600px"
                  #map-canvas style="height: 100%;width:100%"
              #reviews style="#{@open_tab == 'reviews' ? open : hidden}"
                .main_info_text
                  = mail_to('reviews@jstays.com', 'Send us a review!', subject: "My experience with property #{@property.id}")
                -if @property.property_reviews.present?
                  .review_list
                    -@property.property_reviews.each do |review|
                      .review
                        = review.body
                        p Posted: #{review.created_at.to_s}
                -else
                  | Be the first to review

          #details_header Details
          #details
            div
              h3 Description
              = @property.description
              h3 General Comments
              = @property.comments1
              h3 Kashrut
              |Where is this coming from?
        td style="width:40px;"
        / Right side
        td valign="top"
          #price_and_contact_owner
            span PRICE:&nbsp;
            span
              = @property.display_rate
            = link_to image_tag('emailowner.png'), "mailto:#{@property.user.email}"

          #right_info
            table.tabs align="center"
              tbody
                tr
                  th
                  td#at_a_glance_tab.selected
                    = link_to "At a Glance", "javascript:void(0)", onclick: "switch_tab('at_a_glance', 'right_info')"
                  th
                  td#amenities_tab.unselected
                    = link_to "Amenities", "javascript:void(0)", onclick: "switch_tab('amenities', 'right_info')"
                  th
            #right_info_inner
              table#at_a_glance align="center" style="position: static; top: 0px; left: -9999px;"
                tbody
                  tr
                    th.light valign="top" Type
                    td.light valign="top" = PropertyTypes[@property.property_type.to_sym]
                  tr
                    th.dark valign="top" Duration
                    td.dark valign="top" = Duration[@property.duration.to_sym]
                  tr
                    th.light valign="top" Location
                    td.light valign="top" = @property.city
                  tr
                    th.dark valign="top" # Bedrooms
                    td.dark valign="top" = @property.bedrooms
                  tr
                    th.light valign="top" # Bathrooms
                    td.light valign="top" = @property.bathrooms
                  tr
                    th.dark valign="top" # Bed
                    td.dark valign="top" = @property.sleeps
                  tr
                    th.light valign="top" Floor
                    td.light valign="top" = @property.floor
                  tr
                    th.dark valign="top" Other Fees
                    td.dark valign="top" = @property.other_expenses

              table#amenities align="center" style="position: absolute; top: 0px; left: -9999px;"
                tbody
                  tr
                    td.left-side valign="top"
                      -Amenities.slice(0, Amenities.count/2).each do |amenity|
                        div class="#{'found' if @property.amenities && @property.amenities.include?(amenity)}"
                          = amenity
                    td.right-side
                      -Amenities.slice(Amenities.count/2, Amenities.count).each do |amenity|
                        div class="#{'found' if @property.amenities && @property.amenities.include?(amenity)}"
                          = amenity
= link_to "Back to search", search_path

#prop-addr data-lat="#{@property.latitude.round(3)}" data-long="#{@property.longitude.round(3)}"