config/routes.rb
Jstays::Application.routes.draw do

  root  'static_pages#home'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :properties do
    resources :property_pics, shallow: true, only: [:index, :destroy, :create]
    resources :available_dates, shallow: true, only: [:index, :create, :update, :destroy, :set_all] do
      get :set_all, :on => :collection
    end
  end

  get '/search' => 'search#search', :as => 'search'
  get '/about', to: 'static_pages#about'
  get '/faq',   to: 'static_pages#faq'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/available_date.rb
class AvailableDate < ActiveRecord::Base

belongs_to :property

 scope :first_available, -> { where("a_date >= ?", Date.today).order("a_date ASC").first }
 scope :in_month, ->(month, year) { where("MONTH(available_dates.a_date) = ? and YEAR(available_dates.a_date) = ?", month, year ) }
end

app/controllers/available_dates_controller.rb
class AvailableDatesController < ApplicationController
  before_action :set_available_date, only: [:update, :destroy]

  def index
    @property = Property.find(params[:property_id])
    @available_dates = @property.available_dates
    @available_date = AvailableDate.new
    @date = params[:date].present? ? Date.parse(params[:date]) : Date.today
  end

  # def show
  # end

  # def new
  #   @available_date = AvailableDate.new
  # end

  def create
    @available_date = AvailableDate.new(property_id: params[:property_id],
                                        a_date: params[:available_date][:a_date],
                                        level: :low)
    respond_to do |format|
      if @available_date.save
        format.html { redirect_to property_available_dates_path(@available_date.property, date: params[:query_date])}
        format.json { render json: { level: @available_date.level, date_id: @available_date.id, result: 'new' } }
      else
        format.html { redirect_to property_available_dates_path(@available_date.property, date: params[:query_date])}
        format.json { render json: @available_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # def edit
  # end

  def update
    respond_to do |format|
      if @available_date.update(level: :booked)
        format.html { redirect_to property_available_dates_path(@available_date.property, date: params[:query_date])}
        format.json { render json: { level: @available_date.level, date_id: @available_date.id, result: 'updated' } }
      else
        format.html { redirect_to property_available_dates_path(@available_date.property, date: params[:query_date])}
        format.json { render json: @available_date.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property = @available_date.property
    @available_date.destroy
    respond_to do |format|
      format.html { redirect_to property_available_dates_path(@property, date: params[:date]) }
      format.json { render json: { level: 'available', property_id: @property.id, result: 'deleted' } }
    end
  end

  def set_all
    @property = Property.find(params[:property_id])
    start_date  = Date.new(params[:year].to_i, params[:month].to_i, 1)
    end_date    = Date.new(params[:year].to_i, params[:month].to_i + 1, 1) - 1.day
    @property.available_dates.in_month(params[:month], params[:year]).delete_all

    case params[:to_do]
    when 'low'
      (start_date..end_date).each do |date|
        @property.available_dates << AvailableDate.create(a_date: date, level: :low)
      end
    when 'booked'
      (start_date..end_date).each do |date|
        @property.available_dates << AvailableDate.create(a_date: date, level: :booked)
      end
    end
    redirect_to property_available_dates_path(@property, date: params[:date])
  end

  private
    def set_available_date
      @available_date = AvailableDate.find(params[:id])
    end

    def available_date_params
      params[:available_date]
    end
end

app/helpers/available_dates_helper.rb
module AvailableDatesHelper
end

app/views/available_dates/_delete_form.html.slim
= form_for(available_date, :html => {:method => :delete, :class => 'booked available-date', remote: true, :'data-type' => 'json'}) do |f|
  = f.hidden_field :a_date
  = hidden_field_tag :query_date, params[:date]

  .actions
    = f.submit  available_date.a_date.day.to_s

app/views/available_dates/_edit_form.html.slim
= form_for(available_date, :html => {:class => 'low available-date', remote: true, :'data-type' => 'json'}) do |f|
  = f.hidden_field :a_date
  = hidden_field_tag :query_date, params[:date]

  .actions
    = f.submit  available_date.a_date.day.to_s

app/views/available_dates/_embedded_calendar.html.slim
#available-dates-view
  nav#available-dates-nav
    span#previous-four-months.pull-left
      = link_to '<Previous 4 months', property_path(@property, calendar_offset: @month_offset-4, open_tab: 'calendar')
    span#next-four-months.pull-right
      = link_to 'Next 4 months>', property_path(@property, calendar_offset: @month_offset+4, open_tab: 'calendar')

  -@date = Date.today + @month_offset.months
  -[@date, @date+1.month, @date+2.month, @date+3.month].each_with_index do |tdate, idx|
    .month-box
      h2.month-name
        = tdate.strftime('%B %Y')
      = calendar tdate do |date|
        div class="#{@property.available_date(date) ? @property.available_date(date).level : 'available'}"
          = date.day if date.month == tdate.month

app/views/available_dates/_new_form.html.slim
= form_for([@property, available_date], :html => {class: 'available available-date', remote: true, :'data-type' => 'json'}) do |f|
	= f.hidden_field :a_date
	= hidden_field_tag :query_date, params[:date]
	.actions
		= f.submit available_date.a_date.day.to_s

app/views/available_dates/index.html.slim
.h1_wrapper
  h1 Property Vacancy Dates
.main_area
  = render '/properties/sub_menu'
  .intro_area style="text-align:left;"
    | Use this form to set vacancy dates for the property.
      <span class='available-color'>Green</span> indicates that your property is available for rental.
      <span class='booked-color'>Red</span> indicates that your property is booked.
      When you click on a specific date it will change to green, then red then clear.

  center
    #all-month-boxes
      -[@date, @date+1.month, @date+2.month].each_with_index do |tdate, idx|
        .month-box
          h2.month-name
            span.nav-left.pull-left
              =' link_to('<', date: tdate - 3.months) if idx == 0
            = tdate.strftime('%B %Y')
            span.nav-right.pull-right
              = link_to('>', date: tdate.next+1.months) if idx == 2

          .mark-all-buttons
            ' Mark all
            =' link_to '', set_all_property_available_dates_path(@property, date: params[:date], month: tdate.month, year: tdate.year,to_do: 'clear'), class: 'clear'
            =' link_to '' , set_all_property_available_dates_path(@property, date: params[:date], month: tdate.month, year: tdate.year, to_do: 'low'), class: 'low'
            = link_to '' , set_all_property_available_dates_path(@property, date: params[:date], month: tdate.month, year: tdate.year, to_do: 'booked'), class: 'booked'

          = calendar tdate do |date|
            - available_date = @property.available_date(date) || AvailableDate.new(property: @property, level: 'low', a_date: date)
            -if tdate.month != date.month
              = ''
            -elsif available_date.new_record?
              = render('/available_dates/new_form', available_date: available_date)
            -elsif available_date.level == 'low'
              = render('/available_dates/edit_form', available_date: available_date)
            -else
              = render('/available_dates/delete_form',available_date: available_date)
              /= link_to available_date.a_date.day.to_s, available_date_path(available_date, date: params[:date]) ,method: :delete, class: 'high link-as-input'

app/views/available_dates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_available_date_path(@available_date) %> |
<%= link_to 'Back', available_dates_path %>