config/routes.rb
Jstays::Application.routes.draw do

  root  'static_pages#home'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :properties do
    resources :property_pics, shallow: true, only: [:index, :destroy, :create]
    resources :available_dates, shallow: true, only: [:index, :create, :update, :destroy, :set_all] do
      get :set_all, :on => :collection
    end
  end

  get '/search' => 'search#search', :as => 'search'
  get '/about', to: 'static_pages#about'
  get '/faq',   to: 'static_pages#faq'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/views/layouts/_footer.html.slim
#footer-outer-bar
	#footer-inner-bar

table#footer_table.full_table
	tbody
		tr
			td
				2013 Jstays. All Rights Reservered
			td
				= link_to("Feedback", "feedback")
			th |
			td 
				= link_to("Terms & Conditions", "terms_conditions")
			th |
			td 
				= link_to("Privacy Policy", "terms_conditions")
			th |
			td 
				= link_to("Testimonials", "terms_conditions")
			th |
			td 
				= link_to("contact", "contact")
			td width="260px"
			td.icon
				=link_to image_tag("button_fb.gif"), "http://www.facebook.com/JstaysRRR", target: "_blank"
			td.icon
				=link_to image_tag("button_in.gif"), "", target: "_blank"
			td.icon
				=link_to image_tag("button_twitter.gif"), "", target: "_blank"
			td.icon
				=link_to image_tag("button_youtube.gif"), "", target: "_blank"

app/views/layouts/_header.html.slim
table#top_table.full_table
  tr
    td
      nav.pull-right
        ul
          -if signed_in?
            li
              = link_to "My profile", edit_user_path(current_user), title: "#{current_user.email}", class:"gitb-tooltip"
            li
              = link_to "My Properties", properties_path
            li
              = link_to "Sign Out", signout_path, method: "delete"
          -else
            li
              = link_to "Sign In", "#", id: "sign-in-link"
            li
              = link_to 'Register', signup_path
      -if !signed_in?
        #header-sign-in.pull-right
          = form_for(:session, url: sessions_path, :html => {:id => "header-sign-in"}) do |f|
            =' f.label :email
            =' f.text_field :email
            =' f.label :password
            =' f.password_field :password
            = f.submit "Sign in", class: "btn btn-large btn-primary"

app/views/layouts/_subheader.html.slim
table#logo_table.full_table
	tbody
		tr
			td#logo_top
		tr
			td
			    div style="text-align: center; height:74px;"
					= image_tag("logo_tag.png")

		tr
			td
				table#nav.full_table
					tbody
						tr
							td width="50px"
							td#nav_home
								= current_page?('/') ? content_tag(:span, nil, title: 'Home') : link_to('', root_url)
							td#nav_about
								= request.fullpath.include?('about') ? content_tag(:span, nil, title: 'About Us') : link_to('', '/about')
							td#nav_faq
								= request.fullpath.include?('faq') ? content_tag(:span, nil, title: 'FAQ') : link_to('', '/faq')
							td width="430px"
							td#nav_post
								= link_to("", new_property_path)
							td#nav_blog
								= link_to("", '#')

app/views/layouts/application.html.slim
DOCTYPE html
html
	head
		title
			= full_title(yield(:title))
		= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
		meta name="viewport" content="width=device-width, initial-scale=1.0"
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags

	body id="#{params[:controller]}-#{params[:action]}" class="#{params[:controller]} #{params[:action]}"
		center
			= render 'layouts/header'
			= render 'layouts/subheader'

			-flash.each do |key, value|
				.alert class="alert-#{key}"
					= value

			.page-wrapper
				= yield

			= render 'layouts/footer'